require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/clicks", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Click. As you add validations to Click, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Click.create! valid_attributes
      get clicks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      click = Click.create! valid_attributes
      get click_url(click)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_click_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      click = Click.create! valid_attributes
      get edit_click_url(click)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Click" do
        expect {
          post clicks_url, params: { click: valid_attributes }
        }.to change(Click, :count).by(1)
      end

      it "redirects to the created click" do
        post clicks_url, params: { click: valid_attributes }
        expect(response).to redirect_to(click_url(Click.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Click" do
        expect {
          post clicks_url, params: { click: invalid_attributes }
        }.to change(Click, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post clicks_url, params: { click: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested click" do
        click = Click.create! valid_attributes
        patch click_url(click), params: { click: new_attributes }
        click.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the click" do
        click = Click.create! valid_attributes
        patch click_url(click), params: { click: new_attributes }
        click.reload
        expect(response).to redirect_to(click_url(click))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        click = Click.create! valid_attributes
        patch click_url(click), params: { click: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested click" do
      click = Click.create! valid_attributes
      expect {
        delete click_url(click)
      }.to change(Click, :count).by(-1)
    end

    it "redirects to the clicks list" do
      click = Click.create! valid_attributes
      delete click_url(click)
      expect(response).to redirect_to(clicks_url)
    end
  end
end
